---
title: geofileops intro
date: 2024-11-13
---

```{python}
import geofileops as gpo
import geopandas as gpd
from inspect import getmembers, isfunction
```

## Prerequisites
- The input file(s) must be in the same coordinate system.

```{python}
gpo_members = getmembers(gpo, isfunction)
gpo_members = [mem[0] for mem in gpo_members]
```

```{python}
gpo_members
```

- '_get_version'
- 'add_column'
- 'add_layerstyle'
- 'append_to'
- 'apply'
- 'buffer'
- 'clip'
- 'clip_by_geometry'
- 'cmp'
- 'convert'
- 'convexhull'
- 'copy'
- 'copy_layer'
- 'create_spatial_index'
- 'delete_duplicate_geometries'
- 'dissolve'
- 'dissolve_within_distance'
- 'drop_column'
- 'erase'
- 'execute_sql'
- 'export_by_bounds'
- 'export_by_distance'
- 'export_by_location'
- 'get_crs'
- 'get_default_layer'
- 'get_driver'
- 'get_layer_geometrytypes'
- 'get_layerinfo'
- 'get_layerstyles'
- 'get_only_layer'
- 'has_spatial_index'
- 'identity'
- 'intersect'
- 'intersection'
- 'is_geofile'
- 'is_geofile_ext'
- 'is_integer_dtype'
- 'isvalid'
- 'join_by_location'
- 'join_nearest'
- 'listlayers'
- 'makevalid'
- 'move'
- 'read_file'
- 'read_file_nogeom'
- 'read_file_sql'
- 'remove'
- 'remove_layerstyle'
- 'remove_spatial_index'
- 'rename_column'
- 'rename_layer'
- 'select'
- 'select_two_layers'
- 'simplify'
- 'split'
- 'symmetric_difference'
- 'to_file'
- 'union'
- 'update_column'
- 'warp'


```{python}
gpo.buffer(
    input_path = "/home/isong/sf_base.gpkg",
    output_path = "/home/isong/sf_output.gpkg",
    distance = 60)
```

